##
# The "messages" service project defines the functions and API endpoints for 
#  a REST "messages" resource.
# Rather than deploying an entirely new API within API Gateway, the messages 
#  endpoints will be created within the API whose identifer was exported from 
#  the "api" project.
##
service: samples-sacd-messages

custom:
  apiStackName: samples-sacd-base   # The CloudFormation stack name (minus stage) where the API is created.

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128
  timeout: 10
  apiGateway:   # Specify the API to which HTTP endpoints are attached. Reference the Outputs from the API project.
    restApiId: ${cf:${self:custom.apiStackName}-${self:provider.stage}.RestApiId}
    restApiRootResourceId: ${cf:${self:custom.apiStackName}-${self:provider.stage}.RestApiRootResourceId}

functions:
  getMessage:
    handler: index.handler
    events:
      - http: 
          path: /messages/{proxy+}
          method: get
  listMessages:
    handler: index.handler
    events:
      - http: 
          path: /messages
          method: get
