service: samples-rest-cognito-authorizer

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128
  timeout: 6

functions:
  hello:
    handler: index.handler
    events:
      - http: 
          path: hello
          method: get
          authorizer: 
            arn: arn:aws:cognito-idp:us-east-1:123456789012:userpool/us-east-1_07ksBD9fu
