service: samples-custom-domain

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  hello:
    handler: index.handler
    events:
      - http: GET /hello
  goodbye:
    handler: index.handler
    events:
      - http: GET /goodbye
