service: samples-rest-lambda-authorizer

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  memorySize: 128
  timeout: 10

functions:
  hello:
    handler: index.handler
    events:
      - http: 
          path: hello
          method: get
          authorizer: 
            name: simpleTokenAuthorizer
            resultTtlInSeconds: 300     # default response cache time-to-live is 5 minutes
            identitySource: method.request.header.Authorization     # default token location is Authorization header
  simpleTokenAuthorizer:
    handler: authorizer.authorize
